### ISSUE TITLE
Boiler monitoring?

### ISSUE THREAD

**Issue by ErwinP** [Jeroen88/EasyOpenTherm#1]
Hi,

Saw this passing by on Hackster.io, looks super interesting! 
I was wondering, when I hook up my boiler with this, can I use it to monitor rather than control it? With my current thermostat still connected and in control?

Thanks!
Erwin

**Comment by Jeroen88** [comment]
Hi Erwin, no that is not possible. For this purpose you need a _gateway_ to put in between your boiler and thermostat, that acts as a thermostat towards your boiler and as a boiler towards your thermostat. -Jeroen

**Comment by Jeroen88** [comment]
What kind of boiler do you own? I do have hardware and software to read out Remeha boilers, tested on an Avanta. Would you be interested?
