### ISSUE TITLE
Will this work on my analog boiler?

### ISSUE THREAD

**Issue by svenvanhees** [Jeroen88/EasyOpenTherm#13]
Hi,

We have an old boiler that does not support the OpenTherm protocol, but is just an on/off one. Can we still use this on a Wemos D1 mini and connect the 2 boiler wires to the rx/tx on the shield?

In the basic thermostat example, there is this piece of formation. But it does not recognize the current temperature and keeps the heating on indefinitely, even if the setpoint is reached by the onboard temperature sensor.
```
 *    To keep an OpenTherm compatible boiler in OpenTherm mode a message should be send to the boiler by the thermostat at least every second according to the OpenTherm specification.
 *    If the boiler does not receive a message every second it falls back to on/off mode.
 *    This is implemented in this example by running the main loop every second.
```

Would love some help here to make our analog boiler smart. :)

**Comment by Jeroen88** [comment]
Hi @svenvanhees, no that won't work. The OpenTherm protocol is a digital protocol that exchanges digital messages between thermostat and boiler. If the boiler does not support OpenTherm this will not work. 

I can not help you with the old boiler, just two things:

- Why don't you consider buying a new one? If your boiler is really old you will earn your investment back in lower gas consumption
- The on/off protocol is really simple: shortening the two thermostat wires is _on_, and opening them again is _off_. So you could use a relay or a relay board with integrated mircocontroller for this job. I am almost certain that somebody has already made software for this, I think there is even a Home Assistant integration for this. To become (or stay) a little bit efficient in gas usage your boiler should modulate (control the flame depending on the heat demand). If the boiler is not modulating bullet one might be the best solution in the end :)
