### ISSUE TITLE
Compile error advanced thermostat ino

### ISSUE THREAD

**Issue by bwired-nl** [Jeroen88/EasyOpenTherm#14]
Hi Jeroen,

First the connection INO works, i have contact with my boiler (yeah!)
Getting the data id's is also working
I have a ESP32-Wroom-32 (or other esp) and I get some errors during compiling.
Im not so very advanced with arduino ide etc....

I want to use the advanced thermostat.ino

The first is this one
I cannot find the declare for below error. if i remove i get other errors

C:\Users\kn\Documents\Arduino\Advanced_Thermostat\Advanced_Thermostat.ino: In function 'void setup()':
C:\Users\kns\Documents\Arduino\Advanced_Thermostat\Advanced_Thermostat.ino:425:18: error: 'LED_BUILTIN' was not declared in this scope
     digitalWrite(LED_BUILTIN, digitalRead(LED_BUILTIN) == LOW ? HIGH : LOW);
                  ^~~~~~~~~~~
C:\Users\kns\Documents\Arduino\Advanced_Thermostat\Advanced_Thermostat.ino:434:16: error: 'LED_BUILTIN' was not declared in this scope
   digitalWrite(LED_BUILTIN, LOW);
                ^~~~~~~~~~~

exit status 1

Compilation error: 'LED_BUILTIN' was not declared in this scope
I can remove these but get diff error, will show later :-)

also not sure what to do with this: do i need to fill this? guess not
#if !defined(ESP32) && !defined(ESP_LOGE)
#define ESP_LOGE(...)
#define ESP_LOGI(...)
#define ESP_LOGV(...)
#endif

thanks very much

**Comment by bwired-nl** [comment]
after commenting out the digitalwrites I get this error:
i left out a lot more lines in the error below, but hopelfully you can give me a push forward.


c:/users/kn/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\kn\AppData\Local\Temp\arduino\sketches\BEC99140B1D405E6A41216156BD1B00F\libraries\ThermoStateMachine\ThermoStateMachine.cpp.o: in function `ThermoStateMachine::ThermoStateMachine()':
C:\Users\kn\Documents\Arduino\libraries\ThermoStateMachine/ThermoStateMachine.cpp:14: multiple definition of `ThermoStateMachine::ThermoStateMachine()'; C:\Users\kn\AppData\Local\Temp\arduino\sketches\BEC99140B1D405E6A41216156BD1B00F\libraries\OpenThermHelpers\ThermoStateMachine.cpp.o:C:\Users\knuvers\Documents\Arduino\libraries\OpenThermHelpers/ThermoStateMachine.cpp:14: first defined here
c:/users/kn/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\kn\AppData\Local\Temp\arduino\sketches\BEC99140B1D405E6A41216156BD1B00F\libraries\ThermoStateMachine\ThermoStateMachine.cpp.o: in function `ThermoStateMachine::ThermoStateMachine()':
C:\Users\knu\Documents\Arduino\libraries\ThermoStateMachine/ThermoStateMachine.cpp:14: multiple definition of `ThermoStateMachine::ThermoStateMachine()'; 

collect2.exe: error: ld returned 1 exit status

**Comment by Jeroen88** [comment]
Hi @bwired-nl,
LED_BUILTIN should have been defined. This is an error in the board definition you are using. Please check if you compile  for the right board. If so, and the error still remains, just define it yourself. It is the GPIO pin the internal LED on the Wroom development board that you are using. Can be something like:
`#define LED_BUILTIN (2)`
With (2) replaced by the right number of course.

The
`#if !defined(ESP32) && !defined(ESP_LOGE)`
command and the lines following are meant to remove logging if the board is not an ESP32. No need to do anything with it.

Both questions have nothing to do with the library :)

The final error is just what it says: `ThermoStateMachine::ThermoStateMachine()` is defined more than once. It is difficult to help you with this one. Maybe you include files more than once? Maybe you defined it yourself somewhere? I really don't know, can be anything, you have to find that one out yourself I am afraid...
