### ISSUE TITLE
Mqtt

### ISSUE THREAD

**Issue by bwired-nl** [Jeroen88/EasyOpenTherm#3]
Nice project, order the otg controller.
Any update on mqtt?
Thanks!!

**Comment by Jeroen88** [comment]
Hi Pieter, thank you! And thank you for the order, I just shipped it. MQTT will be ready this weekend or the next. I will add it to the examples. Best, Jeroen

**Comment by bwired-nl** [comment]
Great, received it today, will use it soon.👍

**Comment by Jeroen88** [comment]
I just published a first draft example of the MQTT thermostat. It is fully functional (you can subscribe to the room temperature and publish a room setpoint temperature to which the boiler responds) but it is not thoroughly tested yet.

Any comments are welcome! Also please share your ideas around your use cases and heating strategies. I opened up the 'Discussions' section for this.

Enjoy!
